language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
after_success:
  - git fetch --tags; if [[ $(git tag) ]]; then echo \"success\"; else git tag v0.0.0; git push --tags; fi; git fetch --tags
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
